#!/usr/bin/env python3


def hello(name):
    return 'Hello, {}.'.format(name)

def test_hello():
    assert 'Hello, Bob.' == hello('Bob')

if __name__ == '__main__':
    from sys import argv
    print(hello(argv[1]))
